logging:
  level:
    io:
      spring:
        cloud:
          samples: DEBUG

fortune:
  fallbackFortune: Your future is unclear.

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

